MODEL:
  BACKBONE: 'resnet50'
  PRETRAIN_PATH: '/home/zxy/.cache/torch/checkpoints/resnet50-19c8e357.pth'
  ID_LOSS_TYPE: 'cosface' #{'softmax', 'cosface', 'circle'}
  METRIC_LOSS_TYPE: 'triplet'
  POOLING: 'avg'
  MEMORY_BANK: False

INPUT:
  AUGMIX_PROB: 0.0
  AUTOAUG_PROB: 0.0
  COLORJIT_PROB: 0.0
  RE_PROB: 0.0

DATASETS:
  ROOT_DIR: ''
  TRAIN: ('',)
  TEST: ('',)

DATALOADER:
  SAMPLER: 'random_identity' #{'random_identity', 'balanced_identity', 'random'}
  NUM_INSTANCE: 16

SOLVER:
  FP16: True
  BATCH_SIZE: 64
  MAX_EPOCHS: 60
  FREEZE_EPOCHS: 5

  COSINE_MARGIN: 0.35
  COSINE_SCALE: 30

  EVAL_PERIOD: 5