MODEL:
  PRETRAIN_PATH: ''
  ID_LOSS_TYPE: 'cosface' #{'softmax', 'cosface'}
  METRIC_LOSS_TYPE: 'triplet'
  ID_LOSS_MARGIN: 0.35
  ID_LOSS_SCALE: 30

INPUT:
  AUGMIX_PROB: 0.5
  AUTOAUG_PROB: 0.5
  COLORJIT_PROB: 0.5
  RE_PROB: 0.5

DATASETS:
  ROOT_DIR: ''
  TRAIN: ('personx',)
  TEST: ('personx',)

DATALOADER:
  SAMPLER: 'balanced_identity' #{'random_identity', 'balanced_identity', 'random'}
  NUM_INSTANCE: 16

SOLVER:
  FP16: True
  BATCH_SIZE: 64
  MAX_EPOCHS: 50
  FREEZE_EPOCHS: 5